// GENERATED FILE - DO NOT EDIT BY HAND.
// Source: api-liturgia.edicoescnbb.com.br/contents/in/date/YYYY-MM-DD (content.body)

class AclamacaoEvangelho {
  final String referencia;
  final String refrao;
  final String verso;

  const AclamacaoEvangelho({
    required this.referencia,
    required this.refrao,
    required this.verso,
  });
}

const Map<String, AclamacaoEvangelho> aclamacoesEvangelhoPorData = {
  '2026-01-01': AclamacaoEvangelho(referencia: 'Hb 1,1-2', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'De muitos modos, Deus outrora nos falou pelos profetas; nestes tempos derradeiros, nos falou pelo seu Filho.'),
  '2026-01-02': AclamacaoEvangelho(referencia: 'Hb 1,1-2', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Depois de ter falado, no passado, aos nossos pais pelos profetas muitas vezes, em nossos dias Deus falou-nos por seu Filho.'),
  '2026-01-03': AclamacaoEvangelho(referencia: 'Jo 1,14a.12a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A Palavra se fez carne, entre nós ela habitou; e todos os que a acolheram, de Deus filhos se tornaram.'),
  '2026-01-04': AclamacaoEvangelho(referencia: 'cf. Mt 2,2', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vimos sua estrela no Oriente e viemos adorar o Senhor.'),
  '2026-01-05': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus pregava a Boa-Nova, o Reino anunciando, e curava toda espécie de doenças entre o povo.'),
  '2026-01-06': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Espírito do Senhor repousa sobre mim e enviou-me a anunciar aos pobres o Evangelho.'),
  '2026-01-07': AclamacaoEvangelho(referencia: '1Tm 3,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Louvai o Senhor Jesus, todos os povos, aceito pela fé no mundo inteiro!'),
  '2026-01-08': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Espírito do Senhor repousa sobre mim e enviou-me a anunciar aos pobres o Evangelho.'),
  '2026-01-09': AclamacaoEvangelho(referencia: 'Mt 4,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus pregava a Boa-Nova, o Reino anunciando, e curava toda espécie de doenças entre o povo.'),
  '2026-01-10': AclamacaoEvangelho(referencia: 'Mt 4,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O povo, sentado nas trevas, grande luz enxergou; aos que viviam na sombra da morte, resplandeceu-lhes a luz.'),
  '2026-01-11': AclamacaoEvangelho(referencia: 'cf. Mc 9,6', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Abriram-se os céus e fez-se ouvir a voz do Pai: Eis meu filho muito amado; escutai-o, todos vós!'),
  '2026-01-12': AclamacaoEvangelho(referencia: '1Ts 2,13', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Convertei-vos e crede no Evangelho, pois, o Reino de Deus está chegando!'),
  '2026-01-13': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Acolhei a palavra de Deus não como palavra humana, mas como mensagem de Deus, o que ela é, em verdade!'),
  '2026-01-14': AclamacaoEvangelho(referencia: 'Jo 10,27', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Minhas ovelhas escutam minha voz, e as conheço e elas me seguem.'),
  '2026-01-15': AclamacaoEvangelho(referencia: 'Mt 4,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus pregava a Boa-Nova, o Reino anunciando, e curava toda espécie de doenças entre o povo.'),
  '2026-01-16': AclamacaoEvangelho(referencia: 'Lc 7,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Um grande profeta surgiu entre nós e Deus visitou o seu povo, aleluia.'),
  '2026-01-17': AclamacaoEvangelho(referencia: 'Lc 4,18', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Espírito do Senhor repousa sobre mim e enviou-me a anunciar aos pobres o Evangelho.'),
  '2026-01-18': AclamacaoEvangelho(referencia: 'Jo 1,14a.12a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A Palavra se fez carne, entre nós ela acampou; todo aquele que a acolheu, de Deus filho se tornou.'),
  '2026-01-19': AclamacaoEvangelho(referencia: 'Hb 4,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A palavra do Senhor é viva e eficaz: ela julga os pensamentos e as intenções do coração.'),
  '2026-01-20': AclamacaoEvangelho(referencia: 'Ef 1,17-18', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Que o Pai do Senhor Jesus Cristo vos dê do saber o Espírito; para que conheçais a esperança, reservada para vós como herança!'),
  '2026-01-21': AclamacaoEvangelho(referencia: 'Mt 4,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus pregava a Boa-nova, o Reino anunciando, e curava toda espécie de doenças entre o povo.'),
  '2026-01-22': AclamacaoEvangelho(referencia: '2Tm 1,10', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus Cristo salvador destruiu o mal e a morte; fez brilhar pelo Evangelho a luz e a vida imperecíveis.'),
  '2026-01-23': AclamacaoEvangelho(referencia: '2Cor 5,19', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Em Cristo, Deus reconciliou consigo mesmo a humanidade; e a nós ele entregou esta reconciliação.'),
  '2026-01-24': AclamacaoEvangelho(referencia: 'At 16,14b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Abri-nos, ó Senhor, o coração, para ouvirmos a palavra de Jesus!'),
  '2026-01-25': AclamacaoEvangelho(referencia: 'Mt 4,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Pois do Reino a Boa Nova Jesus Cristo anunciava e as dores do seu povo, com poder, Jesus curava.'),
  '2026-01-26': AclamacaoEvangelho(referencia: 'Lucas 4,18', refrao: 'Aleluia, aleluia, aleluia.', verso: 'O Espírito do Senhor repousa sobre mim e enviou-me a anunciar aos pobres o Evangelho'),
  '2026-01-27': AclamacaoEvangelho(referencia: 'Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Graças te dou, ó Pai, Senhor do céu e da terra, pois revelaste os mistérios do seu Reino aos pequeninos, escondendo-os aos doutores!'),
  '2026-01-28': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Semente é de Deus a palavra, o Cristo é o semeador; todo aquele que o encontra, vida eterna encontrou.'),
  '2026-01-29': AclamacaoEvangelho(referencia: 'Sl 118(119),105', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vossa palavra é uma luz para os meus passos, e uma lâmpada luzente em meu caminho.'),
  '2026-01-30': AclamacaoEvangelho(referencia: 'Cf. Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Graças te dou, ó Pai, Senhor do céu e da terra, pois revelaste os mistérios do teu Reino aos pequeninos, escondendo-os aos doutores!'),
  '2026-01-31': AclamacaoEvangelho(referencia: 'Jo 3,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Deus o mundo tanto amou, que lhe deu seu próprio Filho, para todo o que nele crer, encontre a vida eterna.'),
  '2026-02-01': AclamacaoEvangelho(referencia: 'Mt 5,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Meus discípulos, alegrai-vos, exultai de alegria, pois bem grande é a recompensa que nos céus tereis um dia!'),
  '2026-02-02': AclamacaoEvangelho(referencia: 'Lc 2,32', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Sois a luz que brilhará para os gentios, e para a glória de Israel, o vosso povo.'),
  '2026-02-03': AclamacaoEvangelho(referencia: 'Mt 8,17', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Cristo tomou sobre si nossas dores, carregou em seu corpo as nossas fraquezas.'),
  '2026-02-04': AclamacaoEvangelho(referencia: 'Jo 10,27', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Minhas ovelhas escutam minha voz; eu as conheço e elas me seguem.'),
  '2026-02-05': AclamacaoEvangelho(referencia: 'Mc 1,15', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Convertei-vos e crede no Evangelho, pois, o Reino de Deus está chegando!'),
  '2026-02-06': AclamacaoEvangelho(referencia: 'Lc 8,15', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes os que observam a palavra do Senhor, de reto coração, e que produzem muitos frutos, até o fim perseverantes!'),
  '2026-02-07': AclamacaoEvangelho(referencia: 'Jo 10,27', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Minhas ovelhas escutam minha voz, eu as conheço e elas me seguem.'),
  '2026-02-08': AclamacaoEvangelho(referencia: 'Jo 8,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Pois eu sou a luz do mundo, quem nos diz é o Senhor; e vai ter a luz da vida, quem se faz meu seguidor.'),
  '2026-02-09': AclamacaoEvangelho(referencia: 'Mt 4,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus pregava a Boa-nova, o Reino anunciando, e curava toda espécie de doenças entre o povo.'),
  '2026-02-10': AclamacaoEvangelho(referencia: 'Sl 118(119),36.29b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Inclinai meu coração às vossas advertências e dai-me a vossa lei como um presente valioso!'),
  '2026-02-11': AclamacaoEvangelho(referencia: 'Jo 17,17ba', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vossa palavra é a verdade; santificai-nos na verdade!'),
  '2026-02-12': AclamacaoEvangelho(referencia: 'Tg 1,21', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Acolhei docilmente a palavra semeada em vós, meus irmãos; ela pode salvar vossas vidas!'),
  '2026-02-13': AclamacaoEvangelho(referencia: 'At 16,14b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Abri-nos, ó Senhor, o coração para ouvirmos a palavra de Jesus!'),
  '2026-02-14': AclamacaoEvangelho(referencia: 'Mt 4,4b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O homem não vive somente de pão, mas de toda palavra da boca de Deus.'),
  '2026-02-15': AclamacaoEvangelho(referencia: 'Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu te louvo, ó Pai santo, Deus do céu, Senhor da terra: os mistérios do teu reino aos pequenos, Pai, revelas.'),
  '2026-02-16': AclamacaoEvangelho(referencia: 'Jo 14,6', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Sou o Caminho, a Verdade e a Vida, ninguém vem ao Pai, senão por mim.'),
  '2026-02-17': AclamacaoEvangelho(referencia: 'Jo 14,2', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Quem me ama, realmente, guardará minha palavra e meu Pai o amará, e a ele nós viremos.'),
  '2026-02-18': AclamacaoEvangelho(referencia: 'Cf. Sl 94(95),8ab', refrao: 'Jesus Cristo, sois bendito, sois o ungido de Deus Pai!', verso: 'Oxalá ouvísseis hoje a sua voz: não fecheis os corações como em Meriba!'),
  '2026-02-19': AclamacaoEvangelho(referencia: 'Mt 4,17', refrao: 'Glória a vós, Senhor Jesus, primogênito dentre os mortos!', verso: 'Convertei-vos, nos diz o Senhor, está próximo o Reino de Deus!'),
  '2026-02-20': AclamacaoEvangelho(referencia: 'Cf. Am 5,14', refrao: 'Salve, Cristo, luz da vida, companheiro na partilha!', verso: 'Buscai o bem, não o mal, pois assim vivereis; então o Senhor, nosso Deus, convosco estará!'),
  '2026-02-21': AclamacaoEvangelho(referencia: 'Ez 33,11', refrao: 'Glória a vós, Senhor Jesus, Primogênito dentre os mortos!', verso: 'Não quero a morte do pecador, diz o Senhor, mas que ele volte, se converta e tenha vida.'),
  '2026-02-22': AclamacaoEvangelho(referencia: 'Mt 4,4b', refrao: 'Louvor e glória a ti, Senhor, Cristo, Palavra de Deus.', verso: 'O homem não vive somente de pão, mas de toda a palavra da boca de Deus.'),
  '2026-02-23': AclamacaoEvangelho(referencia: '2Cor 6,2b', refrao: 'Salve Cristo, luz da vida, companheiro na partilha!', verso: 'Eis o tempo de conversão; eis o dia da salvação'),
  '2026-02-24': AclamacaoEvangelho(referencia: 'Mt 4,4b', refrao: 'Glória a Cristo, palavra eterna do Pai, que é amor!', verso: 'O homem não vive somente de pão, mas de toda palavra da boca de Deus.'),
  '2026-02-25': AclamacaoEvangelho(referencia: 'Jl 2,12-13', refrao: 'Jesus Cristo, sois bendito, sois o ungido de Deus Pai!', verso: 'Voltai ao Senhor, vosso Deus, ele é bom, compassivo e clemente.'),
  '2026-02-26': AclamacaoEvangelho(referencia: 'Sl 50,12a.14a', refrao: 'Salve, ó Cristo, imagem do Pai, a plena verdade nos comunicai!', verso: 'Criai em mim um coração que seja puro, dai-me de novo a alegria de ser salvo!'),
  '2026-02-27': AclamacaoEvangelho(referencia: 'Ez 18,31', refrao: 'Salve, ó Cristo, imagem do Pai, a plena verdade nos comunicai!', verso: 'Lançai para bem longe toda a vossa iniquidade! Criai em vós um novo espírito e um novo coração!'),
  '2026-02-28': AclamacaoEvangelho(referencia: '2Cor 6,2b', refrao: 'Salve, ó Cristo, imagem do Pai, a plena verdade nos comunicai!', verso: 'Eis o tempo de conversão, eis o dia da salvação.'),
  '2026-03-01': AclamacaoEvangelho(referencia: 'cf. Lc 9,35', refrao: 'Louvor a vós, ó Cristo, rei da eterna glória!', verso: 'Numa nuvem resplendente fez-se ouvir a voz do Pai: Eis meu Filho muito amado, escutai-o, todos vós.'),
  '2026-03-02': AclamacaoEvangelho(referencia: 'Jo 6,63c.68c', refrao: 'Glória a Cristo, palavra eterna do Pai, que é amor!', verso: 'Senhor, tuas palavras são espírito, são vida; só tu tens palavras de vida eterna!'),
  '2026-03-03': AclamacaoEvangelho(referencia: 'Ez 18,31', refrao: 'Salve, ó Cristo, imagem do Pai, a plena verdade nos comunicai!', verso: 'Lançai para bem longe toda a vossa iniquidade! Criai em vós um novo espírito e um novo coração!'),
  '2026-03-04': AclamacaoEvangelho(referencia: 'Jo 8,12', refrao: 'Salve, Cristo, luz da vida, companheiro na partilha!', verso: 'Eu sou a luz do mundo; aquele que me segue não caminha entre as trevas, mas terá a luz da vida'),
  '2026-03-05': AclamacaoEvangelho(referencia: 'Cf. Lc 8,15', refrao: 'Glória a Cristo, palavra eterna do Pai que é amor!', verso: 'Felizes os que observam a palavra do Senhor, de reto coração; e que produzem muitos frutos, até o fim perseverantes!'),
  '2026-03-06': AclamacaoEvangelho(referencia: 'Jo 3,16', refrao: 'Jesus Cristo, sois bendito, sois o Ungido de Deus Pai!', verso: 'Deus o mundo tanto amou que lhe deu seu próprio Filho, para que todo o que nele crer, encontre vida eterna.'),
  '2026-03-07': AclamacaoEvangelho(referencia: 'Lc 15,18', refrao: 'Salve, ó Cristo, imagem do Pai, a plena verdade nos comunicai!', verso: 'Vou voltar e encontrar o meu pai e direi: meu pai, eu pequei contra o céu e contra ti.'),
  '2026-03-08': AclamacaoEvangelho(referencia: 'cf. Jo 4,42.15', refrao: 'Glória e louvor a vós, ó Cristo.', verso: 'Na verdade, sois, Senhor, o Salvador do mundo. Senhor, dai-me água viva a fim de eu não ter sede!'),
  '2026-03-09': AclamacaoEvangelho(referencia: 'Cf. Sl 129(130),5.7', refrao: 'Jesus Cristo, sois bendito, sois o ungido de Deus Pai!', verso: 'No Senhor ponho a minha esperança, espero em sua palavra. Pois no Senhor se encontra toda graça e copiosa redenção.'),
  '2026-03-10': AclamacaoEvangelho(referencia: 'Jl 2,12-13', refrao: 'Jesus Cristo, sois bendito, sois o ungido de Deus Pai!', verso: 'Voltai ao Senhor, vosso Deus, ele é bom, compassivo e clemente.'),
  '2026-03-11': AclamacaoEvangelho(referencia: 'Cf. Jo 6,63c.68c', refrao: 'Glória a Cristo, palavra eterna do Pai, que é amor!', verso: 'Senhor, tuas palavras são espírito, são vida; só tu tens palavras de vida eterna!'),
  '2026-03-12': AclamacaoEvangelho(referencia: 'Jl 2,12-13', refrao: 'Jesus Cristo, sois bendito, sois o ungido de Deus Pai!', verso: 'Voltai ao Senhor, vosso Deus, ele é bom, compassivo e clemente.'),
  '2026-03-13': AclamacaoEvangelho(referencia: 'Mt 4,17', refrao: 'Glória a vós, Senhor Jesus, Primogênito dentre os mortos!', verso: 'Convertei-vos, nos diz o Senhor, está próximo o Reino de Deus!'),
  '2026-03-14': AclamacaoEvangelho(referencia: 'Sl 94(95),8ab', refrao: 'Honra, glória, poder e louvor a Jesus, nosso Deus e Senhor!', verso: 'Oxalá ouvísseis hoje a sua voz: não fecheis os corações como em Meriba!'),
  '2026-03-15': AclamacaoEvangelho(referencia: 'Jo 8,12', refrao: 'Louvor e honra a vós, Senhor Jesus.', verso: 'Pois eu sou a luz do mundo, quem nos diz é o Senhor; e vai ter a luz da vida quem se faz meu seguidor!'),
  '2026-03-16': AclamacaoEvangelho(referencia: 'Cf. Am 5,14', refrao: 'Honra, glória, poder e louvor a Jesus, nosso Deus e Senhor!', verso: 'Buscai o bem, não o mal, pois assim vivereis; então o Senhor, nosso Deus, convosco estará!'),
  '2026-03-17': AclamacaoEvangelho(referencia: 'Sl 50(51),12a.14a', refrao: 'Glória a vós, Senhor Jesus, Primogênito dentre os mortos!', verso: 'Criai em mim um coração que seja puro, dai-me de novo a alegria de ser salvo!'),
  '2026-03-18': AclamacaoEvangelho(referencia: 'Jo 11,25a.26', refrao: 'Jesus Cristo, sois bendito, sois o ungido de Deus Pai!', verso: 'Eu sou a ressurreição, eu sou a vida; Quem crê em mim, ainda que morra, viverá.'),
  '2026-03-19': AclamacaoEvangelho(referencia: '', refrao: 'Louvor e glória a ti, Senhor, Cristo, palavra de Deus!', verso: 'Felizes os que habitam vossa casa, para sempre eles hão de vos louvar!'),
  '2026-03-20': AclamacaoEvangelho(referencia: '', refrao: 'Glória a Cristo, imagem do Pai, a plena verdade nos comunicai!', verso: 'O homem não vive somente de pão, mas de toda palavra da boca de Deus.'),
  '2026-03-21': AclamacaoEvangelho(referencia: 'Lc 8,15', refrao: 'Glória a Cristo, palavra eterna do Pai, que é amor!', verso: 'Felizes os que observam a palavra do Senhor, de reto coração, e produzem muitos frutos, até o fim perseverantes!'),
  '2026-03-22': AclamacaoEvangelho(referencia: 'Jo 11,25a.26', refrao: 'Glória a vós, ó Cristo, verbo de Deus.', verso: 'Eu sou a ressurreição, eu sou a vida. Quem crê em mim não morrerá eternamente.'),
  '2026-03-23': AclamacaoEvangelho(referencia: 'Ez 33,11', refrao: 'Glória a vós, Senhor Jesus, Primogênito dentre os mortos!', verso: 'Não quero a morte do pecador, diz o Senhor, mas que ele volte, se converta e tenha vida.'),
  '2026-03-24': AclamacaoEvangelho(referencia: '', refrao: 'Glória a Cristo, palavra eterna do Pai, que é amor!', verso: 'Semente é de Deus a palavra, Cristo é o semeador; todo aquele que o encontra, vida eterna encontrou.'),
  '2026-03-25': AclamacaoEvangelho(referencia: 'Jo 1,14ab', refrao: 'Glória a Cristo, palavra eterna do Pai, que é amor!', verso: 'A Palavra se fez carne e habitou entre nós. E nós vimos sua glória que recebe de Deus Pai.'),
  '2026-03-26': AclamacaoEvangelho(referencia: 'Cf. Sl 94(95),8ab', refrao: 'Glória a Cristo, Palavra eterna do Pai, que é amor!', verso: 'Oxalá ouvísseis hoje a sua voz. Não fecheis os corações como em Meriba!'),
  '2026-03-27': AclamacaoEvangelho(referencia: 'Cf. Jo 6,63c.68c', refrao: 'Glória a Cristo, Palavra eterna do Pai que é amor!', verso: 'Senhor, tuas palavras são espírito, são vida; só tu tens palavras de vida eterna!'),
  '2026-03-28': AclamacaoEvangelho(referencia: 'Ez 18,31', refrao: 'Salve, ó Cristo, imagem do Pai, a plena verdade nos comunicai!', verso: 'Lançai para bem longe toda a vossa iniquidade! Criai em vós um novo espírito e um novo coração!'),
  '2026-03-29': AclamacaoEvangelho(referencia: 'Fl 2,8-9', refrao: 'Glória e louvor a vós, ó Cristo.', verso: 'Jesus Cristo se tornou obediente, obediente até a morte numa cruz. Pelo que o Senhor Deus o exaltou e deu-lhe um nome muito acima de outro nome.'),
  '2026-03-30': AclamacaoEvangelho(referencia: '', refrao: 'Honra, glória, poder e louvor a Jesus, nosso Deus e Senhor!', verso: 'Salve, nosso rei, somente vós tendes compaixão dos nossos erros.'),
  '2026-03-31': AclamacaoEvangelho(referencia: '', refrao: 'Honra, glória, poder e louvor a Jesus, nosso Deus e Senhor!', verso: 'Salve, ó rei, obediente ao Pai, vós fostes levado para ser crucificado, como um manso cordeiro é conduzido à matança.'),
  '2026-04-01': AclamacaoEvangelho(referencia: '', refrao: 'Salve, Cristo, Luz da vida, companheiro na partilha!', verso: 'Salve, nosso rei, somente vós tendes compaixão dos nossos erros.'),
  '2026-04-02': AclamacaoEvangelho(referencia: 'Is 61,1 (Lc 4,18)', refrao: 'Louvor e honra a vós, Senhor Jesus.', verso: 'O Espírito do Senhor sobre mim fez a sua unção, enviou-me aos empobrecidos a fazer feliz proclamação!'),
  '2026-04-03': AclamacaoEvangelho(referencia: 'Fl 2,8-9', refrao: 'Louvor e honra a vós, Senhor Jesus.', verso: 'Jesus Cristo se tornou obediente, obediente até a morte numa cruz; pelo que o Senhor Deus o exaltou e deu-lhe um nome muito acima de outro nome.'),
  '2026-04-04': AclamacaoEvangelho(referencia: '', refrao: '', verso: ''),
  '2026-04-05': AclamacaoEvangelho(referencia: '1Cor 5,7b-8a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O nosso cordeiro pascal, Jesus Cristo, já foi imolado. Celebremos, assim, esta festa, na sinceridade e verdade.'),
  '2026-04-06': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Este é o dia que o Senhor fez para nós, alegremo-nos e nele exultemos.'),
  '2026-04-07': AclamacaoEvangelho(referencia: 'Sl 117(118),24', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Este é o dia que o Senhor fez para nós, alegremo-nos e nele exultemos!'),
  '2026-04-08': AclamacaoEvangelho(referencia: 'Sl 117(118),24', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Este é o dia que o Senhor fez para nós, alegremo-nos e nele exultemos!'),
  '2026-04-09': AclamacaoEvangelho(referencia: 'Sl 117(118),24', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Este é o dia que o Senhor fez para nós, alegremo-nos e nele exultemos!'),
  '2026-04-10': AclamacaoEvangelho(referencia: 'Sl 117(118),24', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Este é o dia que o Senhor fez para nós, alegremo-nos e nele exultemos!'),
  '2026-04-11': AclamacaoEvangelho(referencia: 'Sl 117(118),24', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Este é o dia que o Senhor fez para nós, alegremo-nos e nele exultemos!'),
  '2026-04-12': AclamacaoEvangelho(referencia: 'Jo 20,29', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Acreditaste, Tomé, porque me viste. Felizes os que creram sem ter visto!'),
  '2026-04-13': AclamacaoEvangelho(referencia: 'Cl 3,1', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Se com Cristo ressurgistes, procurai o que é do alto, onde Cristo está sentado à direita de Deus Pai.'),
  '2026-04-14': AclamacaoEvangelho(referencia: 'Jo 3,14b.15', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Filho do homem há de ser levantado, para que, quem crer, possua a vida eterna.'),
  '2026-04-15': AclamacaoEvangelho(referencia: 'Jo 3,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Deus o mundo tanto amou, que lhe deu seu próprio Filho, para que todo o que nele crer, encontre vida eterna.'),
  '2026-04-16': AclamacaoEvangelho(referencia: 'Jo 20,29', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Acreditaste, Tomé, porque me viste. Felizes os que creem sem ter visto.'),
  '2026-04-17': AclamacaoEvangelho(referencia: 'Mt 4,4b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O homem não vive somente de pão, mas de toda palavra da boca de Deus.'),
  '2026-04-18': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ressurgiu Cristo, o Senhor, que criou tudo; ele teve compaixão da humanidade.'),
  '2026-04-19': AclamacaoEvangelho(referencia: 'Lc 24,32', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Senhor Jesus, revelai-nos o sentido da Escritura; fazei o nosso coração arder, quando nos falardes'),
  '2026-04-20': AclamacaoEvangelho(referencia: 'Mt 4,4b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O homem não vive somente de pão, mas de toda palavra da boca de Deus.'),
  '2026-04-21': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou o pão da vida, quem vem a mim não terá fome; assim nos fala o Senhor.'),
  '2026-04-22': AclamacaoEvangelho(referencia: 'cf. Jo 6,40', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Quem vê o filho e nele crê, este tem a vida eterna, e eu o farei ressuscitar no último dia, diz Jesus.'),
  '2026-04-23': AclamacaoEvangelho(referencia: 'Jo 6,51', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou o pão vivo descido do céu, quem deste pão come, sempre há de viver.'),
  '2026-04-24': AclamacaoEvangelho(referencia: 'Jo 6,56', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Quem come a minha carne e bebe o meu sangue em mim permanece e eu vou ficar nele.'),
  '2026-04-25': AclamacaoEvangelho(referencia: '1Cor 23a.24b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'É Cristo que anunciamos, Jesus Cristo, o Crucificado, poder e sabedoria de Deus.'),
  '2026-04-26': AclamacaoEvangelho(referencia: 'Jo 10,14', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou o bom pastor, diz o Senhor; eu conheço minhas ovelhas e elas me conhecem a mim.'),
  '2026-04-27': AclamacaoEvangelho(referencia: 'Jo 10,14', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou o bom pastor, conheço minhas ovelhas e elas me conhecem, assim fala o Senhor.'),
  '2026-04-28': AclamacaoEvangelho(referencia: 'Jo 10,27', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Minhas ovelhas escutam minha voz, eu as conheço e elas me seguem.'),
  '2026-04-29': AclamacaoEvangelho(referencia: 'Jo 8,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou a luz do mundo; aquele que me segue não caminha entre as trevas, mas terá a luz da vida.'),
  '2026-04-30': AclamacaoEvangelho(referencia: 'Ap 1,5ab', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus Cristo, a fiel testemunha, primogênito dos mortos, nos amou e do pecado nos lavou, em seu sangue derramado.'),
  '2026-05-01': AclamacaoEvangelho(referencia: 'Jo 14,6', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Sou o caminho, a verdade e a vida; ninguém vem ao Pai, senão por mim.'),
  '2026-05-02': AclamacaoEvangelho(referencia: 'Jo 8,31b-32', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Se guardais minha palavra, diz Jesus, realmente vós sereis os meus discípulos.'),
  '2026-05-03': AclamacaoEvangelho(referencia: 'Jo 14,6', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou o Caminho, a Verdade e a Vida. Ninguém chega ao Pai senão por mim.'),
  '2026-05-04': AclamacaoEvangelho(referencia: 'Jo 14,26', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Espírito Santo, o Paráclito, haverá de lembrar-vos de tudo o que tenho falado, aleluia.'),
  '2026-05-05': AclamacaoEvangelho(referencia: 'Lc 24,46.26', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Era preciso que Cristo sofresse e ressuscitasse dos mortos, para entrar em sua glória, aleluia!'),
  '2026-05-06': AclamacaoEvangelho(referencia: 'Jo 15,4a.5b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ficai em mim, e eu em vós ficarei, diz Jesus; quem em mim permanece, há de dar muito fruto.'),
  '2026-05-07': AclamacaoEvangelho(referencia: 'Jo 10,27', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Minhas ovelhas escutam minha voz, minha voz estão elas a escutar; eu conheço, então, minhas ovelhas, que me seguem, comigo a caminhar.'),
  '2026-05-08': AclamacaoEvangelho(referencia: 'Jo 15,15b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu vos chamo meus amigos, pois vos dei a conhecer o que o Pai me revelou.'),
  '2026-05-09': AclamacaoEvangelho(referencia: 'Cl 3,1', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Se com Cristo ressurgistes, procurai o que é do alto, onde Cristo está sentando à direita de Deus Pai.'),
  '2026-05-10': AclamacaoEvangelho(referencia: 'Jo 14,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Quem me ama realmente guardará minha palavra, e meu Pai o amará, e a ele nós viremos.'),
  '2026-05-11': AclamacaoEvangelho(referencia: 'Jo 15,26b.27a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Espírito Santo, a verdade, dará testemunho de mim; depois, também vós, neste mundo, de mim ireis testemunhar.'),
  '2026-05-12': AclamacaoEvangelho(referencia: 'cf. Jo 16,7.13', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu hei de enviar-vos o Espírito da verdade; ele vos conduzirá a toda a verdade.'),
  '2026-05-13': AclamacaoEvangelho(referencia: 'Jo 14,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Rogarei ao meu Pai e ele há de enviar-vos um outro Paráclito, que há de permanecer eternamente convosco.'),
  '2026-05-14': AclamacaoEvangelho(referencia: 'Jo 15,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu vos designei para que vades e deis frutos e o vosso fruto permaneça.'),
  '2026-05-15': AclamacaoEvangelho(referencia: 'Lc 24,46.26', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Era preciso que Cristo sofresse e ressuscitasse dos mortos, para entrar em sua glória.'),
  '2026-05-16': AclamacaoEvangelho(referencia: 'Jo 16,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Saí do Pai e vim ao mundo, eu deixo o mundo e vou ao Pai.'),
  '2026-05-17': AclamacaoEvangelho(referencia: 'Mt 28,19a.20b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ide ao mundo, ensinai aos povos todos; convosco estarei, todo os dias, até o fim dos tempos, diz Jesus.'),
  '2026-05-18': AclamacaoEvangelho(referencia: 'Cl 3,1', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Se com Cristo ressurgistes, procurai o que é do alto, onde Cristo está sentado à direita de Deus Pai.'),
  '2026-05-19': AclamacaoEvangelho(referencia: 'Jo 14,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Rogarei ao meu Pai e ele há de enviar-vos um outro Paráclito, que há de permanecer eternamente convosco.'),
  '2026-05-20': AclamacaoEvangelho(referencia: 'Jo 17,17ba', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vossa palavra é a verdade; santificai-nos na verdade!'),
  '2026-05-21': AclamacaoEvangelho(referencia: 'Jo 17,21', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Para que todos sejam um, diz o Senhor, como tu estás em mim e eu em ti, para que o mundo possa crer que me enviaste.'),
  '2026-05-22': AclamacaoEvangelho(referencia: 'Jo 14,26', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Espírito Santo, o Paráclito, haverá de lembrar-vos de tudo o que tenho falado.'),
  '2026-05-23': AclamacaoEvangelho(referencia: 'Jo 16,7.13', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu hei de enviar-vos o Espírito da verdade; ele vos conduzirá a toda a verdade.'),
  '2026-05-24': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vinde, Espírito divino, e enchei com vossos dons os corações dos fiéis; e acendei neles o amor como um fogo abrasador!'),
  '2026-05-25': AclamacaoEvangelho(referencia: 'Lc 1,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ó feliz Virgem, que geraste o Senhor; ó santa Mãe da Igreja, que nos alimenta com o Espírito do teu Filho, Jesus Cristo.'),
  '2026-05-26': AclamacaoEvangelho(referencia: 'Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Graças te dou, ó Pai, Senhor do céu e da terra, pois, revelaste os mistérios do teu Reino aos pequeninos, escondendo-os aos doutores!'),
  '2026-05-27': AclamacaoEvangelho(referencia: 'Mc 10,45', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Veio o Filho do Homem, a fim de servir e dar sua vida em resgate por muitos.'),
  '2026-05-28': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou a luz do mundo, aquele que me segue, não caminha entre as trevas, mas terá a luz da vida.'),
  '2026-05-29': AclamacaoEvangelho(referencia: 'Jo 15,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu vos escolhi a fim de que deis no meio do mundo, um fruto que dure.'),
  '2026-05-30': AclamacaoEvangelho(referencia: 'Cl 3,16a.17c', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A palavra de Cristo ricamente habite em vós, dando graças, por ele, a Deus Pai!'),
  '2026-05-31': AclamacaoEvangelho(referencia: 'cf. Ap 1,8', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Glória ao Pai e ao Filho e ao Espírito Divino, ao Deus que é, que era e que vem, pelos séculos. Amém!'),
  '2026-06-01': AclamacaoEvangelho(referencia: 'Ap 1,5ab', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus Cristo, a fiel testemunha, primogênito dos mortos, nos amou e do pecado nos lavou, em seu sangue derramado.'),
  '2026-06-02': AclamacaoEvangelho(referencia: 'Ef 1,17-18', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Que o Pai do Senhor Jesus Cristo nos dê do saber o Espírito, para que conheçais a esperança reservada para vós, como herança!'),
  '2026-06-03': AclamacaoEvangelho(referencia: '&nbsp;11,25a.26', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou a ressurreição, eu sou a vida, quem crê em mim, ainda que morra, viverá.'),
  '2026-06-04': AclamacaoEvangelho(referencia: 'Jo 6,51', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou o pão vivo descido do céu; quem deste pão come, sempre há de viver!'),
  '2026-06-05': AclamacaoEvangelho(referencia: 'Jo 14,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Quem me ama, realmente, guardará minha palavra e meu Pai o amará e a ele nós viremos.'),
  '2026-06-06': AclamacaoEvangelho(referencia: 'Mt 5,3', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes os humildes de espírito, porque deles é o Reino dos Céus.'),
  '2026-06-07': AclamacaoEvangelho(referencia: 'Lc 4,18', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Foi o Senhor quem me mandou boas notícias anunciar; ao pobre, a quem está no cativeiro, libertação eu vou proclamar.'),
  '2026-06-08': AclamacaoEvangelho(referencia: 'Mt 5,12a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Alegrai-vos, vós todos, porque grande há de ser a recompensa nos céus que um dia tereis!'),
  '2026-06-09': AclamacaoEvangelho(referencia: 'Mt 5,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vós sois a luz do mundo; brilhe a todos vossa luz. Vendo eles vossas obras, deem glória ao Pai celeste!'),
  '2026-06-10': AclamacaoEvangelho(referencia: 'Sl 24,4b.5a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Fazei-me conhecer vossa estrada, vossa verdade me oriente e me conduza!'),
  '2026-06-11': AclamacaoEvangelho(referencia: 'Mt 28,19a.20b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ide ao mundo e ensinai a todas as nações! Eis que eu estou convosco até o fim do mundo! EVANGELHO (apropriado) De graça recebestes, de graça deveis dar! Proclamação do Evangelho de Jesus Cristo segundo Mateus 10,7-13 Naquele tempo, disse Jesus aos seus discípulos: 7 "Em vosso caminho, anunciai: \'O Reino dos Céus está próximo\'. 8 Curai os doentes, ressuscitai os mortos, purificai os leprosos, expulsai os demônios. De graça recebestes, de graça deveis dar! 9 Não leveis ouro nem prata nem dinheiro nos vossos cintos; 10 nem sacola para o caminho,'),
  '2026-06-12': AclamacaoEvangelho(referencia: 'Mt 11,29', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Tomai sobre vós o meu jugo e de mim aprendei que sou de manso e humilde coração.'),
  '2026-06-13': AclamacaoEvangelho(referencia: 'Lc 2,19', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Bendita é a Virgem Maria, que guardava a Palavra de Deus, meditando-a no seu coração.'),
  '2026-06-14': AclamacaoEvangelho(referencia: 'Mc 1,15', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Reino do céu está perto! Convertei-vos, irmãos, é preciso! Crede todos no Evangelho!'),
  '2026-06-15': AclamacaoEvangelho(referencia: 'Sl 118(119),105', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vossa palavra é uma luz para os meus passos, e uma lâmpada luzente em meu caminho.'),
  '2026-06-16': AclamacaoEvangelho(referencia: 'Jo 13,34', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu vos dou novo preceito: que uns aos outros vos ameis, como eu vos tenho amado.'),
  '2026-06-17': AclamacaoEvangelho(referencia: 'Jo 14,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Quem me ama realmente guardará minha palavra e meu Pai o amará, e a ele nós viremos.'),
  '2026-06-18': AclamacaoEvangelho(referencia: 'Rm 8,15bc', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Recebestes um espírito de adoção, no qual clamamos Aba! Pai!'),
  '2026-06-19': AclamacaoEvangelho(referencia: 'Mt 5,3', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes os humildes de espírito, porque deles é o Reino dos Céus.'),
  '2026-06-20': AclamacaoEvangelho(referencia: '2Cor 8,9', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus Cristo, Senhor nosso, embora sendo rico, para nós se tornou pobre, a fim de enriquecer-nos, mediante sua pobreza.'),
  '2026-06-21': AclamacaoEvangelho(referencia: 'Jo 15,26b.27a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Espírito Santo, a Verdade, de mim irá testemunhar, e vós minhas testemunhas sereis em todo lugar.'),
  '2026-06-22': AclamacaoEvangelho(referencia: 'Hb 4,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A palavra do Senhor é viva e eficaz: ela julga os pensamentos e as intenções do coração.'),
  '2026-06-23': AclamacaoEvangelho(referencia: 'Jo 8,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou a luz do mundo; aquele que me segue não caminha entre as trevas, mas terá a luz da vida.'),
  '2026-06-24': AclamacaoEvangelho(referencia: 'cf. Jo 1,7; Lc 1,17', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'João veio dar testemunho da Luz; a fim de preparar um povo bem disposto, para a vinda do Senhor.'),
  '2026-06-25': AclamacaoEvangelho(referencia: 'Jo 14,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Quem me ama, realmente, guardará minha palavra e meu Pai o amará e a ele nós viremos.'),
  '2026-06-26': AclamacaoEvangelho(referencia: 'Mt 8,17', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Cristo tomou sobre si nossas dores, carregou em seu corpo as nossas fraquezas.'),
  '2026-06-27': AclamacaoEvangelho(referencia: 'Mt 8,17', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Cristo tomou sobre si nossas dores, carregou em seu corpo as nossas fraquezas.'),
  '2026-06-28': AclamacaoEvangelho(referencia: 'Jo 21,17d', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ó Senhor, tu sabes tudo, tu bem sabes que eu te amo!'),
  '2026-06-29': AclamacaoEvangelho(referencia: 'Sl 94(95),8ab', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Oxalá ouvísseis hoje a sua voz: Não fecheis os corações como em Meriba!'),
  '2026-06-30': AclamacaoEvangelho(referencia: 'Sl 129(130),5', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'No Senhor ponho a minha esperança, espero em sua palavra.'),
  '2026-07-01': AclamacaoEvangelho(referencia: 'Tg 1,18', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Deus nos gerou pela palavra da verdade como as primícias de suas criaturas.'),
  '2026-07-02': AclamacaoEvangelho(referencia: '2Cor 5,19', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Em Cristo, Deus reconciliou consigo mesmo a humanidade; e a nós ele entregou essa reconciliação.'),
  '2026-07-03': AclamacaoEvangelho(referencia: 'Jo 20,29', refrao: 'Aleluia, aleluia, aleluia.', verso: 'Acreditaste, Tomé, porque me viste. Felizes os que creem sem ter visto.'),
  '2026-07-04': AclamacaoEvangelho(referencia: 'Jo 10,27', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Minhas ovelhas escutam minha voz, eu as conheço e elas me seguem.'),
  '2026-07-05': AclamacaoEvangelho(referencia: 'Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu te louvo, ó Pai Santo, Deus do céu, Senhor da terra; os mistérios do teu Reino aos pequenos, Pai, revelas!'),
  '2026-07-06': AclamacaoEvangelho(referencia: 'cf. 2Tm 1,10', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus Cristo Salvador destruiu o mal e a morte; fez brilhar, pelo Evangelho, a luz e a vida imperecíveis.'),
  '2026-07-07': AclamacaoEvangelho(referencia: 'Jo 10,14', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou o bom pastor, conheço minhas ovelhas e elas me conhecem, assim fala o Senhor.'),
  '2026-07-08': AclamacaoEvangelho(referencia: 'Mc 1,15', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Convertei-vos e crede no Evangelho, pois, o reino de Deus está chegando!'),
  '2026-07-09': AclamacaoEvangelho(referencia: 'Mc 1,15', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Convertei-vos e crede no Evangelho, pois, o reino de Deus está chegando!'),
  '2026-07-10': AclamacaoEvangelho(referencia: 'Jo 16,13a; 14,26d', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Quando o paráclito vier, o Espírito da verdade, ele vos conduzirá a toda a verdade, lembrar-vos-á de tudo o que eu tenho falado.'),
  '2026-07-11': AclamacaoEvangelho(referencia: '1Pd 4,14', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes sereis vós se fordes ultrajados, por causa de Jesus pois, repousa sobre vós, o Espírito de Deus.'),
  '2026-07-12': AclamacaoEvangelho(referencia: 'Lc 8,11', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Semente é de Deus a Palavra, o Cristo é o semeador; todo aquele que o encontra, vida eterna encontrou!'),
  '2026-07-13': AclamacaoEvangelho(referencia: 'Mt 5,10', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes os que são perseguidos por causa da justiça do Senhor, porque o reino dos céus há de ser deles!'),
  '2026-07-14': AclamacaoEvangelho(referencia: 'cf. Sl 94(95),8ab', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Oxalá ouvísseis hoje a sua voz. Não fecheis os corações como em Meriba!'),
  '2026-07-15': AclamacaoEvangelho(referencia: 'cf. Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Graças te dou, ó Pai, Senhor do céu e da terra, pois, revelaste os mistérios do teu Reino aos pequeninos, escondendo-os aos doutores!'),
  '2026-07-16': AclamacaoEvangelho(referencia: 'Lc 11,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Feliz quem ouve e observa a palavra de Deus!'),
  '2026-07-17': AclamacaoEvangelho(referencia: 'Jo 10,27', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Minhas ovelhas escutam minha voz, eu as conheço e elas me seguem.'),
  '2026-07-18': AclamacaoEvangelho(referencia: '2Cor 5,19', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Em Cristo, Deus reconciliou consigo mesmo a humanidade; e a nós ele entregou esta reconciliação'),
  '2026-07-19': AclamacaoEvangelho(referencia: '13,24-43', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu te louvo, ó Pai Santo, Deus do céu, Senhor da terra: os mistérios do teu Reino aos pequenos, Pai, revelas!'),
  '2026-07-20': AclamacaoEvangelho(referencia: 'cf. Sl 94(95),8ab', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Oxalá ouvísseis hoje a sua voz: Não fecheis os corações como em Meriba!'),
  '2026-07-21': AclamacaoEvangelho(referencia: 'Jo 14,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Quem me ama, realmente, guardará minha palavra e meu Pai o amará, e a ele nós viremos.'),
  '2026-07-22': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Responde-nos, ó Maria, no teu caminho o que havia? Vi Cristo ressuscitado, o túmulo abandonado!'),
  '2026-07-23': AclamacaoEvangelho(referencia: 'cf. Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Graças te dou, ó Pai, Senhor do céu e da terra, pois, revelaste os mistérios do teu Reino aos pequeninos, escondendo-os aos doutores!'),
  '2026-07-24': AclamacaoEvangelho(referencia: 'cf. Lc 8,15', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes os que observam a palavra do Senhor, de reto coração e que produzem muitos frutos, até o fim perseverantes!'),
  '2026-07-25': AclamacaoEvangelho(referencia: 'Jo 15,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu vos designei para que vades e deis frutos, e o vosso fruto permaneça, assim disse o Senhor.'),
  '2026-07-26': AclamacaoEvangelho(referencia: 'Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu te louvo, ó Pai Santo, Deus do céu, Senhor da terra: os mistérios do teu Reino aos pequenos, Pai, revelas!'),
  '2026-07-27': AclamacaoEvangelho(referencia: 'Tg 1,18', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Deus nos gerou pela palavra da verdade como as primícias de suas criaturas!'),
  '2026-07-28': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A semente é de Deus a palavra, o Cristo é o semeador; todo aquele que o encontra, vida eterna encontrou.'),
  '2026-07-29': AclamacaoEvangelho(referencia: 'Jo 8,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou a luz do mundo; aquele que me segue, não caminha entre as trevas, mas terá a luz da vida.'),
  '2026-07-30': AclamacaoEvangelho(referencia: 'cf. At 16,14b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Abre-nos, ó Senhor, o coração, para ouvirmos a palavra de Jesus!'),
  '2026-07-31': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A palavra do Senhor permanece eternamente, e esta é a palavra que vos foi anunciada'),
  '2026-08-01': AclamacaoEvangelho(referencia: 'Mt 5,10', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes os que são perseguidos, por causa da justiça do Senhor, porque o Reino dos céus há de ser deles!'),
  '2026-08-02': AclamacaoEvangelho(referencia: 'cf. Mt 4,4b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O homem não vive somente de pão, mas vive de toda palavra que sai da boca de Deus, e não só de pão. Amém. Aleluia, Aleluia!'),
  '2026-08-03': AclamacaoEvangelho(referencia: 'Mt 4,4', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O homem não vive somente de pão, mas de toda palavra da boca de Deus.'),
  '2026-08-04': AclamacaoEvangelho(referencia: 'Jo 1,49b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Mestre, tu és o Filho de Deus, és rei de Israel!'),
  '2026-08-05': AclamacaoEvangelho(referencia: 'Lc 7,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Um grande profeta surgiu entre nós e Deus visitou o seu povo, aleluia.'),
  '2026-08-06': AclamacaoEvangelho(referencia: 'Mt 17,5c', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eis meu Filho muito amado, nele está meu bem-querer, escutai-o, todos vós!'),
  '2026-08-07': AclamacaoEvangelho(referencia: 'Mt 5,10', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes os que são perseguidos, por causa da justiça do Senhor, porque o Reino dos Céus há de ser deles!'),
  '2026-08-08': AclamacaoEvangelho(referencia: '2Tm 1,10', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus Cristo salvador destruiu o mal e a morte; fez brilhar pelo Evangelho a luz e a vida imperecíveis'),
  '2026-08-09': AclamacaoEvangelho(referencia: 'Sl 129,5', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu confio em nosso Senhor, com fé, esperança e amor; eu espero em sua palavra, hosana, ó Senhor, vem, me salva!'),
  '2026-08-10': AclamacaoEvangelho(referencia: 'Jo 8,12bc', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Aquele que me segue não caminha entre as trevas, mas terá a luz da vida.'),
  '2026-08-11': AclamacaoEvangelho(referencia: 'Mt 11,29ab', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Tomai meu jugo sobre vós e aprendei de mim, que sou de coração humilde e manso!'),
  '2026-08-12': AclamacaoEvangelho(referencia: '2Cor 5,19', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Em Cristo, Deus reconciliou consigo mesmo a humanidade; e a nós ele entregou esta reconciliação.'),
  '2026-08-13': AclamacaoEvangelho(referencia: 'Sl 118 (119),135', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Fazei brilhar vosso semblante ao vosso servo e ensinai-me vossas leis e mandamentos!'),
  '2026-08-14': AclamacaoEvangelho(referencia: '1Ts 2,13', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Acolhei a palavra de Deus, não como palavra humana, mas como mensagem de Deus o que ela é, em verdade!'),
  '2026-08-15': AclamacaoEvangelho(referencia: 'Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Graças te dou, ó Pai, Senhor do céu e da terra, pois revelaste os mistérios do teu Reino aos pequeninos, escondendo-os aos doutores!'),
  '2026-08-16': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes aqueles que ouvem a palavra de Deus e a guardam!'),
  '2026-08-17': AclamacaoEvangelho(referencia: 'Mt 5,3', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes os humildes de espírito, porque deles é o Reino dos Céus.'),
  '2026-08-18': AclamacaoEvangelho(referencia: '2Cor 8,9', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus Cristo, Senhor nosso, embora sendo rico, para nós se tornou pobre, a fim de enriquecer-nos, mediante sua pobreza.'),
  '2026-08-19': AclamacaoEvangelho(referencia: 'Hb 4,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A palavra do Senhor é viva e eficaz: ela julga os pensamentos e as intenções do coração.'),
  '2026-08-20': AclamacaoEvangelho(referencia: 'Cf. Sl 94(95),8ab', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Oxalá ouvísseis hoje a sua voz: Não fecheis os corações como em Meriba!'),
  '2026-08-21': AclamacaoEvangelho(referencia: 'Sl 24,4s', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Fazei-me conhecer vossa estrada, vossa verdade me oriente e me conduza!'),
  '2026-08-22': AclamacaoEvangelho(referencia: 'Cf. Lc 1,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Maria, alegra-te, ó cheia de graça, o Senhor é contigo; és bendita entre todas as mulheres da terra!'),
  '2026-08-23': AclamacaoEvangelho(referencia: 'Mt 16,18', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Tu és Pedro, e sobre esta pedra edificarei minha Igreja; e os poderes do reino das trevas jamais poderão contra ela!'),
  '2026-08-24': AclamacaoEvangelho(referencia: 'Jo 1,49b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Mestre, tu és o filho de Deus, és rei de Israel!'),
  '2026-08-25': AclamacaoEvangelho(referencia: '&nbsp;4,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A palavra do Senhor é viva e eficaz: ela julga os pensamentos e as intenções do coração.'),
  '2026-08-26': AclamacaoEvangelho(referencia: '1Jo 2,5', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O amor de Deus se realiza em todo aquele, que guarda sua palavra fielmente.'),
  '2026-08-27': AclamacaoEvangelho(referencia: 'Mt 24,42a.44', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vigiai, diz Jesus, vigiai, pois, no dia em que não esperais, o vosso Senhor há de vir.'),
  '2026-08-28': AclamacaoEvangelho(referencia: 'Lc 21,36', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vigiai e orai para ficardes de pé, ante o Filho do Homem!'),
  '2026-08-29': AclamacaoEvangelho(referencia: 'Mt 5,10', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes os que são perseguidos, por causa da justiça do Senhor, porque o Reino dos Céus há de ser deles!'),
  '2026-08-30': AclamacaoEvangelho(referencia: 'Ef 1,17-18', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Que o Pai do Senhor Jesus Cristo nos dê do saber o espírito; conheçamos, assim, a esperança à qual nos chamou, como herança!'),
  '2026-08-31': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Espírito do Senhor repousa sobre mim; e enviou-me a anunciar aos pobres o Evangelho.'),
  '2026-09-01': AclamacaoEvangelho(referencia: 'Lc 7,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Um grande profeta surgiu entre nós e Deus visitou o seu povo.'),
  '2026-09-02': AclamacaoEvangelho(referencia: 'Lc 4,18', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Espírito do Senhor repousa sobre mim e enviou-me a anunciar aos pobres o Evangelho.'),
  '2026-09-03': AclamacaoEvangelho(referencia: 'Mt 4,19', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vinde após mim, disse o Senhor, e eu ensinarei a pescar gente.'),
  '2026-09-04': AclamacaoEvangelho(referencia: 'Jo 8,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou a luz do mundo; aquele que me segue não caminha entre as trevas, mas terá a luz da vida.'),
  '2026-09-05': AclamacaoEvangelho(referencia: 'Jo 14,6', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Sou o Caminho, a Verdade e a Vida: ninguém vem ao Pai, senão por mim.'),
  '2026-09-06': AclamacaoEvangelho(referencia: '2Cor 5,19', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Senhor reconciliou o mundo em Cristo, confiando-nos sua Palavra; a Palavra da reconciliação, a Palavra que hoje, aqui, nos salva.'),
  '2026-09-07': AclamacaoEvangelho(referencia: 'Jo&nbsp; 10,27', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Minhas ovelhas escutam minha voz e eu as conheço e elas me seguem.'),
  '2026-09-08': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Sois feliz, virgem Maria; e mereceis todo louvor; pois de vós se levantou o sol brilhante da justiça, que é Cristo, nosso Deus, pelo qual nós fomos salvos!'),
  '2026-09-09': AclamacaoEvangelho(referencia: 'Lc 6,23ab', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Meus discípulos, alegrai-vos, exultai de alegria, pois grande é a recompensa que nos céus tereis um dia!'),
  '2026-09-10': AclamacaoEvangelho(referencia: '1Jo 4,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Se nós nos amamos, irmãos, Deus vive unido conosco, e, em nós seu amor fica pleno!'),
  '2026-09-11': AclamacaoEvangelho(referencia: 'Cf. Jo 17,17b.a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vossa palavra é a verdade; santificai-nos na verdade!'),
  '2026-09-12': AclamacaoEvangelho(referencia: 'Jo 14,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Quem me ama, realmente, guardará minha palavra e meu Pai o amará, e a ele nós viremos'),
  '2026-09-13': AclamacaoEvangelho(referencia: 'Jo 13,34', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu vos dou este novo Mandamento, nova ordem, agora, vos dou; que, também, vos ameis uns aos outros como eu vos amei, diz o Senhor.'),
  '2026-09-14': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Nós vos adoramos, Senhor Jesus Cristo, e vos bendizemos, porque pela cruz remistes o mundo!'),
  '2026-09-15': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Feliz a virgem Maria, que, sem passar pela morte, do martírio ganha a palma, ao pé da cruz do Senhor!'),
  '2026-09-16': AclamacaoEvangelho(referencia: 'Jo 6,63c.68c', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Senhor, tuas palavras são espírito, são vida; só tu tens palavras de vida eterna.'),
  '2026-09-17': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vinde a mim, todos vós que estais cansados, e descanso eu vos darei, diz o Senhor.'),
  '2026-09-18': AclamacaoEvangelho(referencia: 'cf. Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Graças te dou, ó Pai, Senhor do céu e da terra, pois, revelaste os mistérios do teu Reino aos pequeninos, escondendo-os aos doutores!'),
  '2026-09-19': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes os que observam a palavra do Senhor de reto coração, e que produzem muitos frutos, até o fim perseverantes!'),
  '2026-09-20': AclamacaoEvangelho(referencia: 'At 16,14b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vinde abrir o nosso coração, Senhor; ó Senhor, abri o nosso coração, e, então, do vosso filho a palavra, poderemos acolher com muito amor!'),
  '2026-09-21': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A vós, ó Deus, louvamos, a vós, Senhor, cantamos, vos louva, ó Senhor, o coro dos apóstolos.'),
  '2026-09-22': AclamacaoEvangelho(referencia: 'Lc 11,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Feliz quem ouve e observa a palavra de Deus!'),
  '2026-09-23': AclamacaoEvangelho(referencia: 'Mc 1,15', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Convertei-vos e crede no Evangelho, pois, o Reino de Deus está chegando!'),
  '2026-09-24': AclamacaoEvangelho(referencia: 'Jo 14,6', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Sou o caminho, a Verdade e a Vida; ninguém vem ao Pai, senão por mim.'),
  '2026-09-25': AclamacaoEvangelho(referencia: 'Mc 10,45', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Veio o filho do homem, a fim de servir e dar sua vida em resgate por muitos.'),
  '2026-09-26': AclamacaoEvangelho(referencia: 'cf. 2Tm 1,10', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus Cristo salvador destruiu o mal e a morte; fez brilhar pelo Evangelho, a luz e a vida imperecíveis.'),
  '2026-09-27': AclamacaoEvangelho(referencia: 'Jo 10,27', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Minhas ovelhas escutam a minha voz, minha voz estão elas a escutar; eu conheço, então, minhas ovelhas, que me seguem, comigo a caminhar!'),
  '2026-09-28': AclamacaoEvangelho(referencia: 'Mc 10,45', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Veio o filho do homem, a fim de servir dar sua vida em resgate por muitos.'),
  '2026-09-29': AclamacaoEvangelho(referencia: 'Sl 102,21', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Bendizei ao Senhor Deus, os seus poderes, seus ministros que fazeis sua vontade!'),
  '2026-09-30': AclamacaoEvangelho(referencia: 'Fl 3,8-9', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu tudo considero como perda e como lixo, a fim de eu ganhar Cristo e ser achado nele!'),
  '2026-10-01': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Convertei-vos e crede no Evangelho, pois o Reino de Deus está chegando!'),
  '2026-10-02': AclamacaoEvangelho(referencia: 'Sl 102(103),21', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Bendizei ao Senhor Deus, os seus poderes, seus ministros que fazeis sua vontade!'),
  '2026-10-03': AclamacaoEvangelho(referencia: 'cf. Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Graças te dou, ó Pai, Senhor do céu e da terra, pois revelaste os mistérios do teu Reino aos pequeninos, escondendo-os aos doutores!'),
  '2026-10-04': AclamacaoEvangelho(referencia: 'Jo 15,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu vos escolhi, foi do meio do mundo, a fim de que deis um fruto que dure. Eu vos escolhi, foi do meio do mundo. Amém! Aleluia, aleluia!'),
  '2026-10-05': AclamacaoEvangelho(referencia: 'Jo 13,34', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu vos dou novo preceito: que uns aos outros vos ameis, como eu vos tenho amado.'),
  '2026-10-06': AclamacaoEvangelho(referencia: 'Lc 11,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Feliz quem ouve e observa a palavra de Deus!'),
  '2026-10-07': AclamacaoEvangelho(referencia: 'Lc 1,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Maria, alegra-te, ó cheia de graça, o Senhor é contigo; és bendita entre todas as mulheres da terra!'),
  '2026-10-08': AclamacaoEvangelho(referencia: 'Cf. At 16,14b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Abri-nos, ó Senhor, o coração para ouvirmos a palavra de Jesus!'),
  '2026-10-09': AclamacaoEvangelho(referencia: 'Jo 12,31b-32', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Agora o príncipe deste mundo há de ser lançado fora; quando eu for elevado da terra, atrairei para mim todo ser.'),
  '2026-10-10': AclamacaoEvangelho(referencia: 'Lc 11,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Feliz quem ouve e observa a palavra de Deus!'),
  '2026-10-11': AclamacaoEvangelho(referencia: 'Ef 1,17-18', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Que o Pai do Senhor Jesus Cristo nos dê do saber o espírito; conheçamos, assim, a esperança à qual nos chamou, como herança!'),
  '2026-10-12': AclamacaoEvangelho(referencia: 'Jo 2,5b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Disse a mãe de Jesus aos serventes: “Fazei tudo o que Ele disser!”'),
  '2026-10-13': AclamacaoEvangelho(referencia: 'Hb 4,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A palavra do Senhor é viva e eficaz: ela julga os pensamentos e as intenções do coração.'),
  '2026-10-14': AclamacaoEvangelho(referencia: 'Jo 10,27', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Minhas ovelhas escutam minha voz, eu as conheço e elas me seguem.'),
  '2026-10-15': AclamacaoEvangelho(referencia: 'Jo 14,6', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Sou o Caminho, a Verdade e a Vida, ninguém vem ao Pai, senão por mim.'),
  '2026-10-16': AclamacaoEvangelho(referencia: 'Lucas 12,1-7', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Sobre nós venha, Senhor, a vossa graça, da mesma forma que em vós nós esperamos!'),
  '2026-10-17': AclamacaoEvangelho(referencia: 'Jo 15,26b 27a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Espírito Santo, a verdade, de mim irá testemunhar; e vós minhas testemunhas sereis em todo lugar.'),
  '2026-10-18': AclamacaoEvangelho(referencia: 'Fl 2,15d.16a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Como astros no mundo, vós resplandeçais, mensagem de vida ao mundo anunciando, da vida a palavra, com fé, proclameis, quais astros luzentes no mundo brilheis.'),
  '2026-10-19': AclamacaoEvangelho(referencia: 'Mt 5,3', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes os humildes de espírito, porque deles é o Reino dos Céus.'),
  '2026-10-20': AclamacaoEvangelho(referencia: 'Lc 21,36', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vigiai e orai para ficardes de pé, ante o Filho do Homem!'),
  '2026-10-21': AclamacaoEvangelho(referencia: 'Mt 24,42a.44', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vigiai, diz Jesus, vigiai, pois, no dia em que não esperais, o vosso Senhor há de vir.'),
  '2026-10-22': AclamacaoEvangelho(referencia: 'Fl 3,8-9', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu tudo considero como perda e como lixo, a fim de eu ganhar Cristo e ser achado nele!'),
  '2026-10-23': AclamacaoEvangelho(referencia: 'Cf. Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Graças te dou, ó Pai, Senhor do céu e da terra, pois revelaste os mistérios do teu reino aos pequeninos, escondendo-os aos doutores!'),
  '2026-10-24': AclamacaoEvangelho(referencia: 'Ez 33,11', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Não quero a morte do pecador, diz o Senhor, mas que ele volte, se converta e tenha vida'),
  '2026-10-25': AclamacaoEvangelho(referencia: 'Jo 14,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Se alguém me ama, guardará a minha palavra, e meu Pai o amará, e a ele nós viremos.'),
  '2026-10-26': AclamacaoEvangelho(referencia: 'Cf. Jo 17,17ba', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vossa palavra é a verdade; santificai-nos na verdade!'),
  '2026-10-27': AclamacaoEvangelho(referencia: 'Cf. Mt 11,25', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Graças te dou, ó Pai, Senhor do céu e da terra, pois revelaste os mistérios do teu Reino aos pequeninos, escondendo-os aos doutores!'),
  '2026-10-28': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A vós, ó Deus, louvamos, a vós, Senhor, cantamos; vos louva, ó Senhor, o coro dos Apóstolos!'),
  '2026-10-29': AclamacaoEvangelho(referencia: 'Cf. Lc 19,38; 2,14', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Bendito é o rei que vem em nome do Senhor! Glória a Deus nos altos céus e na terra paz aos homens!'),
  '2026-10-30': AclamacaoEvangelho(referencia: 'Jo 10,27', refrao: 'Aleluia, aleluia, aleluia.', verso: 'Minhas ovelhas escutam minha voz, eu as conheço e elas me seguem.'),
  '2026-10-31': AclamacaoEvangelho(referencia: 'Mt 11,29ab', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Tomai meu jugo sobre vós e aprendei de mim, que sou de coração humilde e manso!'),
  '2026-11-01': AclamacaoEvangelho(referencia: 'Mt 11,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vinde a mim, todos vós que estais cansados e penais a carregar pesado fardo, e descanso eu vos darei, diz o Senhor.'),
  '2026-11-02': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'É esta a vontade de quem me enviou: que eu não perca nenhum dos que ele me deu, mas que eu os ressuscite no último dia.'),
  '2026-11-03': AclamacaoEvangelho(referencia: 'Mt 11,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vinde a mim, todos vós que estais cansados, e descanso eu vos darei, diz o senhor.'),
  '2026-11-04': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Felizes sereis vós, se fordes ultrajados por causa de Jesus, pois repousa sobre vós o Espírito de Deus.'),
  '2026-11-05': AclamacaoEvangelho(referencia: 'Mt 11,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vinde a mim, todos vós que estais cansados, e descanso eu vos darei, diz o Senhor.'),
  '2026-11-06': AclamacaoEvangelho(referencia: '1Jo 2,5', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O amor de Deus se realiza em todo aquele, que guarda sua palavra fielmente.'),
  '2026-11-07': AclamacaoEvangelho(referencia: '2Cor 8,9', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Jesus Cristo, Senhor nosso, embora sendo rico, para nós se tornou pobre, a fim de enriquecer-nos mediante sua pobreza.'),
  '2026-11-08': AclamacaoEvangelho(referencia: 'Mt 24,42a.44', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'É preciso vigiar e ficar de prontidão; em que dia o Senhor há de vir, não sabeis não!'),
  '2026-11-09': AclamacaoEvangelho(referencia: '2Cr 7,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Esta casa eu escolhi e santifiquei, para nela estar meu nome para sempre.'),
  '2026-11-10': AclamacaoEvangelho(referencia: 'Jo 14,23', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Quem me ama, realmente, guardará minha palavra, e meu Pai o amará e a ele nós viremos.'),
  '2026-11-11': AclamacaoEvangelho(referencia: '1Ts 5,18', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Em tudo dai graças, pois esta é a vontade de Deus para convosco, em Cristo, o Senhor.'),
  '2026-11-12': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou a videira e vós sois os ramos; um fruto abundante vós haveis de dar.'),
  '2026-11-13': AclamacaoEvangelho(referencia: 'Lc 21,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Levantai vossa cabeça e olhai, pois a vossa redenção se aproxima!'),
  '2026-11-14': AclamacaoEvangelho(referencia: 'Cf. 2Ts 2,14', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Pelo evangelho o Pai nos chamou, a fim de alcançarmos a glória de nosso Senhor Jesus Cristo.'),
  '2026-11-15': AclamacaoEvangelho(referencia: 'Jo 15,4a,5b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ficai em mim, e eu em vós hei de ficar, diz o Senhor; quem em mim permanece, esse dá muito fruto.'),
  '2026-11-16': AclamacaoEvangelho(referencia: 'Jo 8,12', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu sou a luz do mundo; aquele que me segue não caminha entre as trevas, mas terá a luz da vida'),
  '2026-11-17': AclamacaoEvangelho(referencia: '1Jo 4,10b', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Por amor, Deus enviou-nos o seu filho, como vítima por nossas transgressões.'),
  '2026-11-18': AclamacaoEvangelho(referencia: 'Cf. Jo 15,16', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eu vos escolhi, a fim de que deis; no meio do mundo, um fruto que dure.'),
  '2026-11-19': AclamacaoEvangelho(referencia: 'Cf. Sl 94(95), 8ab', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Oxalá ouvísseis hoje a sua voz: Não fecheis os corações como em Meriba!'),
  '2026-11-20': AclamacaoEvangelho(referencia: 'Jo 10,27', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Minhas ovelhas escutam minha voz, eu as conheço e elas me seguem.'),
  '2026-11-21': AclamacaoEvangelho(referencia: 'Lc 11,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Feliz quem ouve e observa a palavra de Deus!'),
  '2026-11-22': AclamacaoEvangelho(referencia: 'Mc 11,10', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'É bendito aquele que vem vindo, que vem vindo em nome do Senhor; e o Reino que vem, seja bendito; ao que vem e a seu Reino, o louvor!'),
  '2026-11-23': AclamacaoEvangelho(referencia: 'Mt 24,42a.44', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vigiai, diz Jesus, vigiai, pois, no dia em que não esperais, o vosso Senhor há de vir.'),
  '2026-11-24': AclamacaoEvangelho(referencia: 'Ap 2,10c', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Permanece fiel até a morte, e a coroa da vida eu te darei!'),
  '2026-11-25': AclamacaoEvangelho(referencia: 'Ap 2,10c', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Permanece fiel até a morte e a coroa da vida eu te darei!'),
  '2026-11-26': AclamacaoEvangelho(referencia: 'Lc 21,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Levantai vossa cabeça e olhai, pois a vossa redenção se aproxima!'),
  '2026-11-27': AclamacaoEvangelho(referencia: 'Lc 21,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Levantai vossa cabeça e olhai, pois a vossa redenção se aproxima!'),
  '2026-11-28': AclamacaoEvangelho(referencia: 'Lc 21,36', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vigiai e orai para ficardes de pé, ante o filho do Homem!'),
  '2026-11-29': AclamacaoEvangelho(referencia: 'Sl 84,8', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Mostrai-nos, ó Senhor, vossa bondade, e a vossa salvação nos concedei!'),
  '2026-11-30': AclamacaoEvangelho(referencia: 'Mt 4,19', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vinde após mim, disse o Senhor, e eu ensinarei a pescar gente.'),
  '2026-12-01': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eis que virá o nosso Deus com poder e majestade. E ele há de iluminar os olhos dos seus servos.'),
  '2026-12-02': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eis que o Senhor há de vir a fim de salvar o seu povo; Felizes são todos aqueles que estão prontos para ir-lhe ao encontro.'),
  '2026-12-03': AclamacaoEvangelho(referencia: 'Is 55,6', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Buscai o Senhor, vosso Deus, invocai-o enquanto está perto!'),
  '2026-12-04': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eis que virá o nosso Deus com poder e majestade, E ele há de iluminar os olhos dos seus servos!'),
  '2026-12-05': AclamacaoEvangelho(referencia: 'Is 33,22', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'É o Senhor nosso juiz e nosso Rei. O Senhor legislador nos salvará.'),
  '2026-12-06': AclamacaoEvangelho(referencia: 'Lc 3,4.6', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Preparai o caminho do Senhor; endireitai suas veredas. Toda a carne há de ver a salvação do nosso Deus.'),
  '2026-12-07': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eis que o rei há de vir, Senhor da terra, ele mesmo de nós afastará o jugo do nosso cativeiro.'),
  '2026-12-08': AclamacaoEvangelho(referencia: 'Cf. Lc 1,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Maria, alegra-te, ó cheia de graça, o Senhor é contigo!'),
  '2026-12-09': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eis que o Senhor há de vir, a fim de salvar o seu povo; felizes são todos aqueles que estão prontos para ir-lhe ao encontro.'),
  '2026-12-10': AclamacaoEvangelho(referencia: 'Is 45,8', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Que os céus, lá do alto, derramem o orvalho, que chova das nuvens o Justo esperado, que a terra se abra e germine o Senhor!'),
  '2026-12-11': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Senhor há de vir, acorrei-lhe ao encontro; é o Príncipe da paz.'),
  '2026-12-12': AclamacaoEvangelho(referencia: 'Cf. Lc 1,28', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Maria, alegra-te, ó cheia de graça, o Senhor é contigo; és bendita entre todas as mulheres da terra!'),
  '2026-12-13': AclamacaoEvangelho(referencia: 'Is 61,1 (Lc 4,18)', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'O Espírito do Senhor sobre mim fez a sua unção, enviou-me aos empobrecidos a fazer feliz proclamação.'),
  '2026-12-14': AclamacaoEvangelho(referencia: 'Sl 84(85),8', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Mostrai-nos, ó Senhor, vossa bondade e a vossa salvação nos concedei!'),
  '2026-12-15': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Vinde, ó Senhor, não tardeis mais; fazei o povo acabar com os seus crimes.'),
  '2026-12-16': AclamacaoEvangelho(referencia: 'Is 40,9-10', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Tu que trazes boa-nova a Sião, levanta tua voz e anuncia: eis que vem o Senhor Deus com poderio!'),
  '2026-12-17': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ó Sabedoria do Altíssimo, que tudo determina com doçura e com vigor: oh, vem nos ensinar o caminho da prudência!'),
  '2026-12-18': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ó Guia de Israel, que no monte do Sinai orientastes a Moisés, oh, vinde redimir-nos, com braço estendido!'),
  '2026-12-19': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ó Raiz de Jessé, sinal das nações: oh, vinde livrar-nos, e não tardeis mais!'),
  '2026-12-20': AclamacaoEvangelho(referencia: 'Lc 1,38', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Eis a serva do Senhor; cumpra-se em mim a tua palavra!'),
  '2026-12-21': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ó Emanuel, sois nosso rei e orientador: vinde salvar-nos, ó Senhor e nosso Deus!'),
  '2026-12-22': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ó Rei e Senhor das nações, e pedra angular da Igreja, vinde salvar a mulher e o homem, que, um dia, formastes do barro.'),
  '2026-12-23': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ó Rei e Senhor das nações e Pedra angular da Igreja, vinde salvar a mulher e o homem, que, um dia, formastes do barro.'),
  '2026-12-24': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Ó Sol da manhã, ó Sol de justiça, da eterna luz esplendor: oh, vinde brilhar para o povo sentado, na sombra da morte.'),
  '2026-12-25': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Glória a Deus nos altos céus, e paz na terra entre os homens, que ele ama. Aleluia.'),
  '2026-12-26': AclamacaoEvangelho(referencia: 'Sl 117(118),26a.27a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Bendito o que vem em nome do Senhor. Nosso Deus é o Senhor, ele é a nossa luz.'),
  '2026-12-27': AclamacaoEvangelho(referencia: 'Cl 3,15a.16a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Que a paz de Cristo reine em vossos corações e ricamente habite em vós sua palavra!'),
  '2026-12-28': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A vós, ó Deus, louvamos, a vós, Senhor, cantamos; vos louva o exército dos vossos santos mártires!'),
  '2026-12-29': AclamacaoEvangelho(referencia: 'Lc 2,32', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Sois a luz que brilhará para os gentios e para a glória de Israel, o vosso povo .'),
  '2026-12-30': AclamacaoEvangelho(referencia: '', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'Um dia sagrado brilhou para nós: Nações, vinde todas adorar o Senhor: pois hoje desceu grande luz sobre a terra!'),
  '2026-12-31': AclamacaoEvangelho(referencia: 'Jo 1,14a.12a', refrao: 'Aleluia, Aleluia, Aleluia.', verso: 'A palavra se fez carne, entre nós ela habitou; e todos os que a acolheram, de Deus filhos se tornaram.'),
};
